### ISSUE TITLE
Link to Core Values file in job postings returns 404

### ISSUE THREAD

**Issue by barlowst** [fishtown-analytics/corp#108]
The link to the company values is broken for at least a few of the job postings. 

I saw this on the following job postings:

Engineering Manager, Cloud Application
https://boards.greenhouse.io/dbtlabsinc/jobs/4350465005

Engineering Manager, dbt Explorer
https://boards.greenhouse.io/dbtlabsinc/jobs/4351839005

For both of those, the bullet point "Aligns with [our core values" points to https://github.com/fishtown-analytics/corp/blob/master/values.md."

That link returns a 404. 

I did notice that the posting for Engineering Manager, Orchestration (https://boards.greenhouse.io/dbtlabsinc/jobs/4326424005) works fine since it points to your webpage:  https://www.getdbt.com/dbt-labs/values

I hope this channel is ok to report this - I would want someone to tell me and since the 404 was in this git repo it seemed the most obvious way.

**Comment by joellabes** [comment]
Thanks for the heads up @barlowst! We'll get these updated 👀

**Comment by barlowst** [comment]
Yep, just confirming -  works as expected for me too (well, the first one is gone, but I assume that is expected and the role was filled).
